### ISSUE TITLE
watcher breaks partially good strings with separators

### ISSUE THREAD

**Issue by Babay88** [zsavely/PatternedTextWatcher#22]
1. create PatternedTextWatcher with pattern "##.##.####"
2. type in some text. for example 11.12.1234
3. replace text with "11.12.34" (from code, using EditText.setText())

expected result:
text should remain as it was replaced: "11.12.34"

actual result:
text replaced with: "11..1.2.34"; separators inserted where they already are

**Comment by zsavely** [comment]
Thanks for the report. I reproduced it, will try to fix asap.

**Comment by zsavely** [comment]
You should try `compile 'com.szagurskii:patternedtextwatcher:0.6.0-SNAPSHOT'`. Your issue should be fixed there.

**Comment by Babay88** [comment]
thank you
