### ISSUE TITLE
watcher breaks strings when delete characters at random intermediate position and then continued to add new characters from that position

### ISSUE THREAD

**Issue by dsimeonov140** [zsavely/PatternedTextWatcher#27]
1. create PatternedTextWatcher with pattern "####-##-## ##:##".
2. type in some text. for example "2018-12-30 12:00".
3. go after "2018-12" and delete "12"

expected result: "2018--30 12:00" and position of cursor to be between "--"
actual result: "2018--30 12:0" (yes, last number is gone) and cursor goes after "2018" before "--", and if you add something between "--" all is messed up.

**Comment by Angels-group** [comment]
Is the problem still unsolved?

**Comment by zsavely** [comment]
The project is no longer maintained. I will deprecate it ASAP.
