### ISSUE TITLE
Copy Pasting Some String Does not work properly

### ISSUE THREAD

**Issue by faiz786** [zsavely/PatternedTextWatcher#28]
If  i am copying some string into edit text id does not follow the pattern

**Comment by zsavely** [comment]
Hey @faiz786,
I don't maintain this project anymore. If you want, you can either try and make a pull request or become a maintainer.

Thanks!

**Comment by zsavely** [comment]
@faiz786 try this project, it's maintained: https://github.com/RedMadRobot/input-mask-android
